import { test, expect, createTeam, startEvent, loginTeam, assignSecrets } from './fixtures'

test('ARENA-001/002/006 and GUESS-001: arena exposes difficulty and one-guess state', async ({ adminPage, browser }) => {
  const team = await createTeam(adminPage, 'Arena')
  await assignSecrets(adminPage, team.username)
  await startEvent(adminPage)
  const context = await browser.newContext()
  const page = await context.newPage()
  await loginTeam(page, team)
  await expect(page.getByTestId('team-name')).toContainText('E2E-ARENA')
  await expect(page.getByTestId('team-score')).toBeVisible()
  await expect(page.getByTestId('difficulty-1')).toBeVisible()
  await expect(page.getByTestId('difficulty-2')).toBeVisible()
  await expect(page.getByTestId('difficulty-3')).toBeVisible()
  await expect(page.getByTestId('guess-status-1')).toHaveText('1 GUESS REMAINING')
  await context.close()
})

test('CHAT-001/002/003/005/008 and BROWSER-008: chat UI accepts a controlled response', async ({ adminPage, browser }) => {
  const team = await createTeam(adminPage, 'Chat')
  await assignSecrets(adminPage, team.username)
  await startEvent(adminPage)
  const context = await browser.newContext()
  const page = await context.newPage()
  await loginTeam(page, team)
  await page.route('**/functions/v1/chat-gateway', async (route) => {
    await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ answer: 'Controlled clue response' }) })
  })
  await page.getByTestId('chat-submit').click()
  await expect(page.getByTestId('chat-input')).toBeEnabled()
  await page.getByTestId('chat-input').fill('Give me a safe clue')
  await page.getByTestId('chat-submit').click()
  await expect(page.getByTestId('chat-history')).toContainText('Controlled clue response')
  await page.getByTestId('clear-chat').click()
  await expect(page.getByTestId('chat-history')).not.toContainText('Controlled clue response')
  await context.close()
})

test('GUESS-004/007/010/011: a successful guess disables the difficulty', async ({ adminPage, browser }) => {
  const team = await createTeam(adminPage, 'Guess')
  await assignSecrets(adminPage, team.username)
  await startEvent(adminPage)
  const context = await browser.newContext()
  const page = await context.newPage()
  await loginTeam(page, team)
  const secret = process.env.E2E_TEAM_SECRET_EASY
  if (!secret) throw new Error('E2E_TEAM_SECRET_EASY is required.')
  await page.getByTestId('guess-input').fill(secret)
  await page.getByTestId('guess-submit').click()
  await expect(page.getByTestId('guess-status-1')).toHaveText('GUESS USED')
  await expect(page.getByTestId('guess-input')).toBeDisabled()
  await expect(page.getByTestId('guess-submit')).toBeDisabled()
  await context.close()
})
